### ISSUE TITLE
Proposal: 'entrance' key

### ISSUE THREAD

**Issue by juliuste** [derhuerst/vbb-station-photos#12]
I'd like to propose a `building` or `entrance` key, since some stations have some architecturally relevant or appealing entrance buildings we might want to cover as well.
For stations without any special entrance, we could either set this key to `null` or use an image of this station's 'boring' standard Berlin metro entrance.

### *Relevant** entrances

- [Krumme Lanke](https://commons.wikimedia.org/wiki/File:Berlin_-_U-Bahnhof_Krumme_Lanke_-_Linie_U3_(6268024794).jpg) (U3)
- [Nollendorfplatz](https://commons.wikimedia.org/wiki/File:Berlin_-_U-Bahnhof_Nollendorfplatz_(11279316253).jpg) (U1, U2, U3, U4)
- [Wittenbergplatz](https://commons.wikimedia.org/wiki/File:Berlin,_Schoeneberg,_Wittenbergplatz,_U-Bahnhof_Wittenbergplatz.jpg) (U1, U2, U3)

### Standard entrances

- [Kaiserdamm](https://commons.wikimedia.org/wiki/File:U-Bahnhof_Kaiserdamm_20141110_4.jpg) (U2)
- [Rathaus Spandau](https://commons.wikimedia.org/wiki/File:U-Bahn_Berlin_Rathaus_Spandau_Eingang.jpg) (U7) *this one might be controversal 😆*
- [Frankfurter Allee](https://commons.wikimedia.org/wiki/File:U-Bahnhof_Frankfurter_Allee_(13607233625).jpg) (U5)

Final note: If we decide to implement this, we probably have to change the structure of the data, since everything is line-specific right now, this might not be too useful when talking about entrance buildings. Or maybe it is, I can't really tell.

_*In my opinion_

**Comment by derhuerst** [comment]
👍 I guess even the boring entrances are useful, as they can be used as a guiding example of how to find and enter the subway station. If you want, submit a PR!

*Rathaus Spandau* ist indeed controversial. 😛

**Comment by juliuste** [comment]
> Final note: If we decide to implement this, we probably have to change the structure of the data, since everything is line-specific right now, this might not be too useful when talking about entrance buildings. Or maybe it is, I can't really tell.

Nevermind, since different lines could have different entrance buildings, I would propose adding a per-line `entrance` key, so that a station would be represented like this, which wouldn't require any changes to the existing structure:

```js
'900000026101': { // U Neu-Westend
	U2:  {label: ['flickr', 'ingolfbln', 15021410257], platform: ['flickr', 'ingolfbln', 15184959836], entrance: ['commons', 'entranceNeuWestend.jpeg']},
	U10: {label: ['commons', 'someFile.jpeg'], platform: ['commons', 'otherFile.png'], entrance: ['commons', 'entranceNeuWestend.jpeg']}
}
```

**Comment by juliuste** [comment]
#13
